name: Bug Report
description: Report a regression or defect in Sakaimachi Bus Mini.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the problem and the observed behaviour.
      placeholder: >-
        e.g. "Countdown stops updating after switching direction"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Impact
      options:
        - Blocker (service unusable)
        - High (core flow broken)
        - Medium (annoying but has workaround)
        - Low (minor polish)
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser / OS / Device and build info.
      placeholder: "Safari 17.5 on iOS 17.4"
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
  - type: textarea
    id: attachments
    attributes:
      label: Additional Context
      description: Logs, screenshots, related issues, etc.
